# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a2cd0ac92abc53ad567279514fc3a0f13b8c281df73a2b0943f0497e0fe2584a1d9977195f4e53d6cc06701081815e6ff81a9bf9d381a41bcb403c49b93ed5f

test:
  secret_key_base: 34362838558827a187e1645ead4fd781c50f3c09d6f451101e4f89713de3b1c156b5d650352abd840e9f424554e8febe11b75d777fb34c672fa62ba5cf38486f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
